name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'
  release:
    types:
      - created

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'release' && github.event.action == 'created')

    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create and use a new builder instance
      run: docker buildx create --use

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ github.event_name == 'push' && format('david1155/estherbot:{0}', github.ref_name) || '' }}
          ${{ github.event_name == 'release' && 'david1155/estherbot:latest' || '' }}
